# Generated by Django 5.0 on 2023-12-07 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='hospital.patienthistory'),
        ),
    ]
